title: Kang Zhao Homepage
description: Kang Zhao, Zhao Kang, SJTU, ZJU, zk1818kid, Kang
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kang Zhao # add your name
author-img: kang.jpg # add your photo
about-author: Algorithm Engineer<br>Alibaba Damo Academy
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: zk1818kid # add your Github handle
social-linkedin: kang-z-96a2bba5
social-email: zhaokang0826@gmail.com
social-google:

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
